// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoCFwz_NJzW05Tv8dDjK5QyAXRv8BZubs',
    appId: '1:519371653363:web:6091399672a73d1d957786',
    messagingSenderId: '519371653363',
    projectId: 'foundit-6bc8a',
    authDomain: 'foundit-6bc8a.firebaseapp.com',
    storageBucket: 'foundit-6bc8a.firebasestorage.app',
    measurementId: 'G-F1BG8KQYP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MHJYcieASePHk34v_XzbQHFt6o1C8gY',
    appId: '1:519371653363:android:bd6d850a26e553d1957786',
    messagingSenderId: '519371653363',
    projectId: 'foundit-6bc8a',
    storageBucket: 'foundit-6bc8a.firebasestorage.app',
  );
}
